name: Norma CI

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:  # Run on pull requests
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Midnight PST (8:00 UTC)

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Platforms to test
        julia-version: ["1.10", "1.11"]  # Julia versions to test
    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      # Step 3: Remove existing Manifest.toml
      - name: Remove existing Manifest.toml
        run: rm -f Manifest.toml

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate()'

      # Step 5: Run the tests
      - name: Run tests
        run: |
          julia --project=. -e 'using Pkg; Pkg.test()'

