name: Norma CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Midnight PST (8:00 UTC)

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        julia-version: ["1.10", "1.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Remove existing Manifest.toml
        run: rm -f Manifest.toml

      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.test()'
