name: Norma CI

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:  # Run on pull requests
  schedule:
    - cron: '0 8 * * *'  # Midnight PST (8:00 UTC)

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Platforms to test
        julia-version: ["1.10", "1.11"]  # Julia versions to test
    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate()'

      # Step 4: Run the tests
      - name: Run tests
        run: |
          julia --project=. -e 'using Pkg; Pkg.test()'

      # Step 5: Upload test results (optional)
      - name: Upload test results
        if: always()  # Run this even if the test step fails
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.log

